import { StyleSheet, Platform } from 'react-native';
import { colors } from '@/constants/colors';
import { fonts } from '@/constants/fonts';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  headerContainer: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceHighlight,
    borderBottomWidth: 1,
    borderColor: colors.border,
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginTop: 20,
  },
  headerIndicator: {
    width: 6,
    backgroundColor: colors.primary,
    marginRight: 16,
    transform: [{ skewX: '-10deg' }],
  },
  headerContent: {
    flex: 1,
    gap: 4,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerTitle: {
    fontFamily: fonts.headline,
    fontSize: 24,
    color: colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontStyle: 'italic',
  },
  headerSubtitle: {
    fontFamily: fonts.body,
    fontSize: 12,
    color: colors.text.secondary,
  },
  scroll: {
    padding: 20,
    paddingBottom: 100,
  },
  mainContent: {
    flexDirection: 'column',
    gap: 24,
    width: '100%',
  },
  teamSection: {
    width: '100%',
  },
  rightPanel: {
    width: '100%',
    gap: 24,
  },
  powerRatingBox: {
    backgroundColor: colors.surfaceHighlight,
    borderWidth: 2,
    borderColor: colors.secondary,
    padding: 16,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 5,
  },
  powerIconBg: {
    position: 'absolute',
    right: -20,
    top: 10,
    opacity: 0.3,
  },
  powerRatingTitle: {
    fontFamily: fonts.bodyBold,
    fontSize: 12,
    color: colors.secondary,
    letterSpacing: 2,
    marginBottom: 4,
  },
  powerRatingValue: {
    fontFamily: fonts.headline,
    fontSize: 42,
    color: colors.text.primary,
    letterSpacing: 2,
    marginBottom: 16,
    textShadowColor: 'rgba(255,255,255,0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  statBox: {
    flex: 1,
    backgroundColor: colors.surface,
    padding: 8,
    borderLeftWidth: 2,
    borderColor: colors.border,
  },
  statTitle: {
    fontFamily: fonts.body,
    fontSize: 9,
    color: colors.text.secondary,
    marginBottom: 4,
  },
  statValue: {
    fontFamily: fonts.bodyBold,
    fontSize: 14,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  startButton: {
    flexDirection: 'row',
    backgroundColor: colors.secondary,
    paddingVertical: 16,
    paddingHorizontal: 40,
    alignItems: 'center',
    
    gap: 16,
    transform: [{ skewX: '-15deg' }],
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 15,
    elevation: 8,
  },
  startButtonPressed: {
    shadowOpacity: 0.4,
    shadowRadius: 5,
  },
  startButtonText: {
    fontFamily: fonts.headline,
    fontSize: 28,
    color: colors.background,
    letterSpacing: 2,
    fontStyle: 'italic',
    transform: [{ skewX: '15deg' }],
  },
});
