import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/colors';

export const styles = StyleSheet.create({
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContainer: {
        width: '100%',
        maxWidth: 400,
        backgroundColor: Colors.surface,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: Colors.border,
        overflow: 'hidden',
        maxHeight: '90%',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: Colors.border,
        backgroundColor: Colors.surfaceHighlight,
    },
    headerTitle: {
        color: Colors.text.primary,
        fontSize: 18,
        fontWeight: 'bold',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    closeButton: {
        padding: 4,
    },
    scrollContent: {
        paddingBottom: 24,
    },
    imageContainer: {
        width: '100%',
        height: 250,
        backgroundColor: '#1A1A1A',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
        borderBottomWidth: 1,
        borderBottomColor: Colors.border,
    },
    image: {
        width: '80%',
        height: '80%',
    },
    idBadge: {
        position: 'absolute',
        top: 16,
        left: 16,
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: Colors.border,
    },
    idText: {
        color: Colors.text.secondary,
        fontSize: 14,
        fontWeight: 'bold',
        fontFamily: 'monospace',
    },
    infoSection: {
        padding: 24,
    },
    pokemonName: {
        color: Colors.text.primary,
        fontSize: 28,
        fontWeight: 'bold',
        textTransform: 'uppercase',
        textAlign: 'center',
        marginBottom: 16,
        textShadowColor: Colors.primary,
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 10,
    },
    typesContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 12,
        marginBottom: 24,
    },
    typeBadge: {
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 20,
        backgroundColor: Colors.surfaceHighlight,
        borderWidth: 1,
        borderColor: Colors.border,
    },
    typeText: {
        color: Colors.text.primary,
        fontSize: 12,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    divider: {
        height: 1,
        backgroundColor: Colors.border,
        marginVertical: 16,
    },
    sectionTitle: {
        color: Colors.text.primary,
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 16,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    statsContainer: {
        gap: 12,
    },
    statRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    statLabel: {
        color: Colors.text.secondary,
        fontSize: 12,
        fontWeight: 'bold',
        width: 60,
    },
    statBarBg: {
        flex: 1,
        height: 8,
        backgroundColor: Colors.surfaceHighlight,
        borderRadius: 4,
        marginHorizontal: 12,
        overflow: 'hidden',
    },
    statBarFill: {
        height: '100%',
        borderRadius: 4,
    },
    statValue: {
        color: Colors.text.primary,
        fontSize: 12,
        fontWeight: 'bold',
        width: 30,
        textAlign: 'right',
    },
});
