import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  rightSide: {
    flex: 1,
    backgroundColor: '#0D1117',
    position: 'relative',
    overflow: 'hidden',
  },
  authBackgroundText: {
    position: 'absolute',
    bottom: -30,
    right: -20,
    fontSize: 180,
    fontWeight: '900',
    color: '#1A222E',
    opacity: 0.3,
    fontStyle: 'italic',
  },
  formScrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  formContainer: {
    width: '100%',
    maxWidth: 400,
  },
  formHeader: {
    marginBottom: 40,
  },
  formTitleCyan: {
    color: '#00D2FF',
    fontSize: 32,
    fontWeight: '900',
    fontStyle: 'italic',
    letterSpacing: 1,
    textShadowColor: '#00D2FF',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  formTitleWhite: {
    color: '#FFFFFF',
    fontSize: 32,
    fontWeight: '900',
    fontStyle: 'italic',
    letterSpacing: 1,
    marginTop: -5,
  },
  headerUnderline: {
    width: 60,
    height: 4,
    backgroundColor: '#00D2FF',
    marginTop: 20,
  },
  inputGroup: {
    marginBottom: 24,
  },
  inputLabel: {
    color: '#00D2FF',
    fontSize: 12,
    fontWeight: 'bold',
    letterSpacing: 2,
    marginBottom: 8,
  },
  inputWrapper: {
    backgroundColor: '#1E2532',
    borderRadius: 4,
    height: 50,
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  input: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 14,
    ...Platform.select({
      web: { outlineStyle: 'none' }
    }),
  },
  formOptions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 40,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkbox: {
    width: 18,
    height: 18,
    backgroundColor: '#1E2532',
    borderWidth: 1,
    borderColor: '#334155',
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 2,
  },
  checkboxChecked: {
    borderColor: '#00D2FF',
  },
  checkboxLabel: {
    color: '#8A95A5',
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  forgotText: {
    color: '#00D2FF',
    fontSize: 11,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  primaryButton: {
    backgroundColor: '#82D8FF',
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#82D8FF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 20,
    elevation: 10,
    transform: [{ skewX: '-5deg' }],
  },
  primaryButtonText: {
    color: '#0A0E14',
    fontSize: 18,
    fontWeight: '900',
    fontStyle: 'italic',
    letterSpacing: 2,
    transform: [{ skewX: '5deg' }],
  },
  secondaryButton: {
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFC800',
    marginBottom: 40,
    transform: [{ skewX: '-5deg' }],
  },
  secondaryButtonText: {
    color: '#FFC800',
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 2,
    transform: [{ skewX: '5deg' }],
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#1E293B',
  },
  dividerText: {
    color: '#475569',
    fontSize: 10,
    fontWeight: 'bold',
    letterSpacing: 2,
    paddingHorizontal: 16,
  },
  socialButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
  },
  socialButton: {
    width: 48,
    height: 48,
    borderWidth: 1,
    borderColor: '#1E293B',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0D1117',
  }
});
